image: hosttoday/ht-docker-node:npmts

stages:
  - test
  - release
    
testLEGACY:
  stage: test
  script:
    - npmci test legacy
  only:
    - master
  tags:
    - docker
    - lossless

testLTS:
  stage: test
  script:
    - npmci test lts
  only:
    - master
  tags:
    - docker
    - lossless

testSTABLE:
  stage: test
  script:
    - npmci test stable
  only:
    - master
  tags:
    - docker
    - lossless

release:
  stage: release
  script:
    - npmci publish npm
  only:
    - master
  tags:
    - lossless